/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mailslurp.Model;
using mailslurp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mailslurp.Test.Model
{
    /// <summary>
    ///  Class for testing EmailThreadProjection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmailThreadProjectionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmailThreadProjection
        //private EmailThreadProjection instance;

        public EmailThreadProjectionTests()
        {
            // TODO uncomment below to create an instance of EmailThreadProjection
            //instance = new EmailThreadProjection();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailThreadProjection
        /// </summary>
        [Fact]
        public void EmailThreadProjectionInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmailThreadProjection
            //Assert.IsType<EmailThreadProjection>(instance);
        }

        /// <summary>
        /// Test the property 'Sender'
        /// </summary>
        [Fact]
        public void SenderTest()
        {
            // TODO unit test for the property 'Sender'
        }

        /// <summary>
        /// Test the property 'Recipients'
        /// </summary>
        [Fact]
        public void RecipientsTest()
        {
            // TODO unit test for the property 'Recipients'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'InboxId'
        /// </summary>
        [Fact]
        public void InboxIdTest()
        {
            // TODO unit test for the property 'InboxId'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

        /// <summary>
        /// Test the property 'Cc'
        /// </summary>
        [Fact]
        public void CcTest()
        {
            // TODO unit test for the property 'Cc'
        }

        /// <summary>
        /// Test the property 'Bcc'
        /// </summary>
        [Fact]
        public void BccTest()
        {
            // TODO unit test for the property 'Bcc'
        }

        /// <summary>
        /// Test the property 'HasAttachments'
        /// </summary>
        [Fact]
        public void HasAttachmentsTest()
        {
            // TODO unit test for the property 'HasAttachments'
        }

        /// <summary>
        /// Test the property 'LastBodyExcerpt'
        /// </summary>
        [Fact]
        public void LastBodyExcerptTest()
        {
            // TODO unit test for the property 'LastBodyExcerpt'
        }

        /// <summary>
        /// Test the property 'LastTextExcerpt'
        /// </summary>
        [Fact]
        public void LastTextExcerptTest()
        {
            // TODO unit test for the property 'LastTextExcerpt'
        }

        /// <summary>
        /// Test the property 'LastCreatedAt'
        /// </summary>
        [Fact]
        public void LastCreatedAtTest()
        {
            // TODO unit test for the property 'LastCreatedAt'
        }

        /// <summary>
        /// Test the property 'LastFrom'
        /// </summary>
        [Fact]
        public void LastFromTest()
        {
            // TODO unit test for the property 'LastFrom'
        }

        /// <summary>
        /// Test the property 'LastSender'
        /// </summary>
        [Fact]
        public void LastSenderTest()
        {
            // TODO unit test for the property 'LastSender'
        }

        /// <summary>
        /// Test the property 'MessageCount'
        /// </summary>
        [Fact]
        public void MessageCountTest()
        {
            // TODO unit test for the property 'MessageCount'
        }

        /// <summary>
        /// Test the property 'Unread'
        /// </summary>
        [Fact]
        public void UnreadTest()
        {
            // TODO unit test for the property 'Unread'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
    }
}
