/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mailslurp.Model;
using mailslurp.Client;
using System.Reflection;

namespace mailslurp.Test.Model
{
    /// <summary>
    ///  Class for testing EmailFeatureOverview
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmailFeatureOverviewTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmailFeatureOverview
        //private EmailFeatureOverview instance;

        public EmailFeatureOverviewTests()
        {
            // TODO uncomment below to create an instance of EmailFeatureOverview
            //instance = new EmailFeatureOverview();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailFeatureOverview
        /// </summary>
        [Fact]
        public void EmailFeatureOverviewInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmailFeatureOverview
            //Assert.IsType<EmailFeatureOverview>(instance);
        }

        /// <summary>
        /// Test the property 'Feature'
        /// </summary>
        [Fact]
        public void FeatureTest()
        {
            // TODO unit test for the property 'Feature'
        }

        /// <summary>
        /// Test the property 'Statuses'
        /// </summary>
        [Fact]
        public void StatusesTest()
        {
            // TODO unit test for the property 'Statuses'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

        /// <summary>
        /// Test the property 'NotesNumbers'
        /// </summary>
        [Fact]
        public void NotesNumbersTest()
        {
            // TODO unit test for the property 'NotesNumbers'
        }

        /// <summary>
        /// Test the property 'FeatureStatistics'
        /// </summary>
        [Fact]
        public void FeatureStatisticsTest()
        {
            // TODO unit test for the property 'FeatureStatistics'
        }
    }
}
