/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mailslurp.Api;
using mailslurp.Model;
using mailslurp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mailslurp.Test.Model
{
    /// <summary>
    ///  Class for testing GenerateTlsReportingRecordOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenerateTlsReportingRecordOptionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GenerateTlsReportingRecordOptions
        //private GenerateTlsReportingRecordOptions instance;

        public GenerateTlsReportingRecordOptionsTests()
        {
            // TODO uncomment below to create an instance of GenerateTlsReportingRecordOptions
            //instance = new GenerateTlsReportingRecordOptions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GenerateTlsReportingRecordOptions
        /// </summary>
        [Fact]
        public void GenerateTlsReportingRecordOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" GenerateTlsReportingRecordOptions
            //Assert.IsType<GenerateTlsReportingRecordOptions>(instance);
        }


        /// <summary>
        /// Test the property 'ReportingAddresses'
        /// </summary>
        [Fact]
        public void ReportingAddressesTest()
        {
            // TODO unit test for the property 'ReportingAddresses'
        }
        /// <summary>
        /// Test the property 'ReportingUrl'
        /// </summary>
        [Fact]
        public void ReportingUrlTest()
        {
            // TODO unit test for the property 'ReportingUrl'
        }
        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Fact]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'Ttl'
        /// </summary>
        [Fact]
        public void TtlTest()
        {
            // TODO unit test for the property 'Ttl'
        }

    }

}
