/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mailslurp.Model;
using mailslurp.Client;
using System.Reflection;

namespace mailslurp.Test.Model
{
    /// <summary>
    ///  Class for testing PhoneNumberDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PhoneNumberDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PhoneNumberDto
        //private PhoneNumberDto instance;

        public PhoneNumberDtoTests()
        {
            // TODO uncomment below to create an instance of PhoneNumberDto
            //instance = new PhoneNumberDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhoneNumberDto
        /// </summary>
        [Fact]
        public void PhoneNumberDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PhoneNumberDto
            //Assert.IsType<PhoneNumberDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

        /// <summary>
        /// Test the property 'PhoneCountry'
        /// </summary>
        [Fact]
        public void PhoneCountryTest()
        {
            // TODO unit test for the property 'PhoneCountry'
        }

        /// <summary>
        /// Test the property 'PhonePlan'
        /// </summary>
        [Fact]
        public void PhonePlanTest()
        {
            // TODO unit test for the property 'PhonePlan'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'Favourite'
        /// </summary>
        [Fact]
        public void FavouriteTest()
        {
            // TODO unit test for the property 'Favourite'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'ComplianceAddress'
        /// </summary>
        [Fact]
        public void ComplianceAddressTest()
        {
            // TODO unit test for the property 'ComplianceAddress'
        }

        /// <summary>
        /// Test the property 'EmergencyAddress'
        /// </summary>
        [Fact]
        public void EmergencyAddressTest()
        {
            // TODO unit test for the property 'EmergencyAddress'
        }
    }
}
