/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mailslurp.Model;
using mailslurp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mailslurp.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateDeliverabilityTestOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateDeliverabilityTestOptionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateDeliverabilityTestOptions
        //private UpdateDeliverabilityTestOptions instance;

        public UpdateDeliverabilityTestOptionsTests()
        {
            // TODO uncomment below to create an instance of UpdateDeliverabilityTestOptions
            //instance = new UpdateDeliverabilityTestOptions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateDeliverabilityTestOptions
        /// </summary>
        [Fact]
        public void UpdateDeliverabilityTestOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateDeliverabilityTestOptions
            //Assert.IsType<UpdateDeliverabilityTestOptions>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'StartAt'
        /// </summary>
        [Fact]
        public void StartAtTest()
        {
            // TODO unit test for the property 'StartAt'
        }

        /// <summary>
        /// Test the property 'MaxDurationSeconds'
        /// </summary>
        [Fact]
        public void MaxDurationSecondsTest()
        {
            // TODO unit test for the property 'MaxDurationSeconds'
        }

        /// <summary>
        /// Test the property 'ClearMaxDuration'
        /// </summary>
        [Fact]
        public void ClearMaxDurationTest()
        {
            // TODO unit test for the property 'ClearMaxDuration'
        }

        /// <summary>
        /// Test the property 'SuccessThresholdPercent'
        /// </summary>
        [Fact]
        public void SuccessThresholdPercentTest()
        {
            // TODO unit test for the property 'SuccessThresholdPercent'
        }

        /// <summary>
        /// Test the property 'ClearSuccessThreshold'
        /// </summary>
        [Fact]
        public void ClearSuccessThresholdTest()
        {
            // TODO unit test for the property 'ClearSuccessThreshold'
        }

        /// <summary>
        /// Test the property 'Expectations'
        /// </summary>
        [Fact]
        public void ExpectationsTest()
        {
            // TODO unit test for the property 'Expectations'
        }
    }
}
