/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = mailslurp.Client.OpenAPIDateConverter;

namespace mailslurp.Model
{
    /// <summary>
    /// Entity-level deliverability result
    /// </summary>
    [DataContract(Name = "DeliverabilityEntityResultDto")]
    public partial class DeliverabilityEntityResultDto : IValidatableObject
    {
        /// <summary>
        /// Defines PhoneCountry
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum PhoneCountryEnum
        {
            /// <summary>
            /// Enum US for value: US
            /// </summary>
            [EnumMember(Value = "US")]
            US = 1,

            /// <summary>
            /// Enum GB for value: GB
            /// </summary>
            [EnumMember(Value = "GB")]
            GB = 2,

            /// <summary>
            /// Enum AU for value: AU
            /// </summary>
            [EnumMember(Value = "AU")]
            AU = 3,

            /// <summary>
            /// Enum CA for value: CA
            /// </summary>
            [EnumMember(Value = "CA")]
            CA = 4,

            /// <summary>
            /// Enum EE for value: EE
            /// </summary>
            [EnumMember(Value = "EE")]
            EE = 5,

            /// <summary>
            /// Enum HK for value: HK
            /// </summary>
            [EnumMember(Value = "HK")]
            HK = 6,

            /// <summary>
            /// Enum PL for value: PL
            /// </summary>
            [EnumMember(Value = "PL")]
            PL = 7,

            /// <summary>
            /// Enum PT for value: PT
            /// </summary>
            [EnumMember(Value = "PT")]
            PT = 8,

            /// <summary>
            /// Enum NL for value: NL
            /// </summary>
            [EnumMember(Value = "NL")]
            NL = 9,

            /// <summary>
            /// Enum IL for value: IL
            /// </summary>
            [EnumMember(Value = "IL")]
            IL = 10,

            /// <summary>
            /// Enum FI for value: FI
            /// </summary>
            [EnumMember(Value = "FI")]
            FI = 11,

            /// <summary>
            /// Enum SE for value: SE
            /// </summary>
            [EnumMember(Value = "SE")]
            SE = 12
        }


        /// <summary>
        /// Gets or Sets PhoneCountry
        /// </summary>
        [DataMember(Name = "phoneCountry", EmitDefaultValue = true)]
        public PhoneCountryEnum? PhoneCountry { get; set; }
        /// <summary>
        /// Defines PhoneVariant
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum PhoneVariantEnum
        {
            /// <summary>
            /// Enum LOCAL for value: LOCAL
            /// </summary>
            [EnumMember(Value = "LOCAL")]
            LOCAL = 1,

            /// <summary>
            /// Enum MOBILE for value: MOBILE
            /// </summary>
            [EnumMember(Value = "MOBILE")]
            MOBILE = 2,

            /// <summary>
            /// Enum TOLLFREE for value: TOLL_FREE
            /// </summary>
            [EnumMember(Value = "TOLL_FREE")]
            TOLLFREE = 3
        }


        /// <summary>
        /// Gets or Sets PhoneVariant
        /// </summary>
        [DataMember(Name = "phoneVariant", EmitDefaultValue = true)]
        public PhoneVariantEnum? PhoneVariant { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeliverabilityEntityResultDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DeliverabilityEntityResultDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeliverabilityEntityResultDto" /> class.
        /// </summary>
        /// <param name="entityId">entityId (required).</param>
        /// <param name="entityLabel">entityLabel (required).</param>
        /// <param name="matched">matched (required).</param>
        /// <param name="matchedExpectationCount">matchedExpectationCount (required).</param>
        /// <param name="totalExpectationCount">totalExpectationCount (required).</param>
        /// <param name="phoneCountry">phoneCountry.</param>
        /// <param name="phoneVariant">phoneVariant.</param>
        /// <param name="evaluatedAt">evaluatedAt.</param>
        /// <param name="expectationResults">expectationResults (required).</param>
        public DeliverabilityEntityResultDto(Guid entityId = default, string entityLabel = default, bool matched = default, int matchedExpectationCount = default, int totalExpectationCount = default, PhoneCountryEnum? phoneCountry = default, PhoneVariantEnum? phoneVariant = default, DateTime? evaluatedAt = default, List<DeliverabilityExpectationResultDto> expectationResults = default)
        {
            this.EntityId = entityId;
            // to ensure "entityLabel" is required (not null)
            if (entityLabel == null)
            {
                throw new ArgumentNullException("entityLabel is a required property for DeliverabilityEntityResultDto and cannot be null");
            }
            this.EntityLabel = entityLabel;
            this.Matched = matched;
            this.MatchedExpectationCount = matchedExpectationCount;
            this.TotalExpectationCount = totalExpectationCount;
            // to ensure "expectationResults" is required (not null)
            if (expectationResults == null)
            {
                throw new ArgumentNullException("expectationResults is a required property for DeliverabilityEntityResultDto and cannot be null");
            }
            this.ExpectationResults = expectationResults;
            this.PhoneCountry = phoneCountry;
            this.PhoneVariant = phoneVariant;
            this.EvaluatedAt = evaluatedAt;
        }

        /// <summary>
        /// Gets or Sets EntityId
        /// </summary>
        [DataMember(Name = "entityId", IsRequired = true, EmitDefaultValue = true)]
        public Guid EntityId { get; set; }

        /// <summary>
        /// Gets or Sets EntityLabel
        /// </summary>
        [DataMember(Name = "entityLabel", IsRequired = true, EmitDefaultValue = true)]
        public string EntityLabel { get; set; }

        /// <summary>
        /// Gets or Sets Matched
        /// </summary>
        [DataMember(Name = "matched", IsRequired = true, EmitDefaultValue = true)]
        public bool Matched { get; set; }

        /// <summary>
        /// Gets or Sets MatchedExpectationCount
        /// </summary>
        [DataMember(Name = "matchedExpectationCount", IsRequired = true, EmitDefaultValue = true)]
        public int MatchedExpectationCount { get; set; }

        /// <summary>
        /// Gets or Sets TotalExpectationCount
        /// </summary>
        [DataMember(Name = "totalExpectationCount", IsRequired = true, EmitDefaultValue = true)]
        public int TotalExpectationCount { get; set; }

        /// <summary>
        /// Gets or Sets EvaluatedAt
        /// </summary>
        [DataMember(Name = "evaluatedAt", EmitDefaultValue = true)]
        public DateTime? EvaluatedAt { get; set; }

        /// <summary>
        /// Gets or Sets ExpectationResults
        /// </summary>
        [DataMember(Name = "expectationResults", IsRequired = true, EmitDefaultValue = true)]
        public List<DeliverabilityExpectationResultDto> ExpectationResults { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeliverabilityEntityResultDto {\n");
            sb.Append("  EntityId: ").Append(EntityId).Append("\n");
            sb.Append("  EntityLabel: ").Append(EntityLabel).Append("\n");
            sb.Append("  Matched: ").Append(Matched).Append("\n");
            sb.Append("  MatchedExpectationCount: ").Append(MatchedExpectationCount).Append("\n");
            sb.Append("  TotalExpectationCount: ").Append(TotalExpectationCount).Append("\n");
            sb.Append("  PhoneCountry: ").Append(PhoneCountry).Append("\n");
            sb.Append("  PhoneVariant: ").Append(PhoneVariant).Append("\n");
            sb.Append("  EvaluatedAt: ").Append(EvaluatedAt).Append("\n");
            sb.Append("  ExpectationResults: ").Append(ExpectationResults).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
