/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = mailslurp.Client.OpenAPIDateConverter;

namespace mailslurp.Model
{
    /// <summary>
    /// Matches for the given pattern
    /// </summary>
    [DataContract(Name = "EmailContentMatchResult")]
    public partial class EmailContentMatchResult : IEquatable<EmailContentMatchResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailContentMatchResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EmailContentMatchResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailContentMatchResult" /> class.
        /// </summary>
        /// <param name="pattern">pattern (required).</param>
        /// <param name="matches">matches (required).</param>
        public EmailContentMatchResult(string pattern = default(string), List<string> matches = default(List<string>))
        {
            // to ensure "pattern" is required (not null)
            if (pattern == null)
            {
                throw new ArgumentNullException("pattern is a required property for EmailContentMatchResult and cannot be null");
            }
            this.Pattern = pattern;
            // to ensure "matches" is required (not null)
            if (matches == null)
            {
                throw new ArgumentNullException("matches is a required property for EmailContentMatchResult and cannot be null");
            }
            this.Matches = matches;
        }

        /// <summary>
        /// Gets or Sets Pattern
        /// </summary>
        [DataMember(Name = "pattern", IsRequired = true, EmitDefaultValue = true)]
        public string Pattern { get; set; }

        /// <summary>
        /// Gets or Sets Matches
        /// </summary>
        [DataMember(Name = "matches", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Matches { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmailContentMatchResult {\n");
            sb.Append("  Pattern: ").Append(Pattern).Append("\n");
            sb.Append("  Matches: ").Append(Matches).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EmailContentMatchResult);
        }

        /// <summary>
        /// Returns true if EmailContentMatchResult instances are equal
        /// </summary>
        /// <param name="input">Instance of EmailContentMatchResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmailContentMatchResult input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Pattern == input.Pattern ||
                    (this.Pattern != null &&
                    this.Pattern.Equals(input.Pattern))
                ) && 
                (
                    this.Matches == input.Matches ||
                    this.Matches != null &&
                    input.Matches != null &&
                    this.Matches.SequenceEqual(input.Matches)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Pattern != null)
                {
                    hashCode = (hashCode * 59) + this.Pattern.GetHashCode();
                }
                if (this.Matches != null)
                {
                    hashCode = (hashCode * 59) + this.Matches.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
