// <auto-generated>
/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using mailslurp.Client;

namespace mailslurp.Model
{
    /// <summary>
    /// Result of search for inbox by email address
    /// </summary>
    public partial class InboxByEmailAddressResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InboxByEmailAddressResult" /> class.
        /// </summary>
        /// <param name="exists">exists</param>
        /// <param name="inboxId">inboxId</param>
        [JsonConstructor]
        public InboxByEmailAddressResult(bool exists, Option<Guid?> inboxId = default)
        {
            Exists = exists;
            InboxIdOption = inboxId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Exists
        /// </summary>
        [JsonPropertyName("exists")]
        public bool Exists { get; set; }

        /// <summary>
        /// Used to track the state of InboxId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> InboxIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets InboxId
        /// </summary>
        [JsonPropertyName("inboxId")]
        public Guid? InboxId { get { return this.InboxIdOption; } set { this.InboxIdOption = new Option<Guid?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InboxByEmailAddressResult {\n");
            sb.Append("  Exists: ").Append(Exists).Append("\n");
            sb.Append("  InboxId: ").Append(InboxId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InboxByEmailAddressResult" />
    /// </summary>
    public class InboxByEmailAddressResultJsonConverter : JsonConverter<InboxByEmailAddressResult>
    {
        /// <summary>
        /// Deserializes json to <see cref="InboxByEmailAddressResult" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InboxByEmailAddressResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> exists = default;
            Option<Guid?> inboxId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "exists":
                            exists = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "inboxId":
                            inboxId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!exists.IsSet)
                throw new ArgumentException("Property is required for class InboxByEmailAddressResult.", nameof(exists));

            if (exists.IsSet && exists.Value == null)
                throw new ArgumentNullException(nameof(exists), "Property is not nullable for class InboxByEmailAddressResult.");

            return new InboxByEmailAddressResult(exists.Value.Value, inboxId);
        }

        /// <summary>
        /// Serializes a <see cref="InboxByEmailAddressResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="inboxByEmailAddressResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InboxByEmailAddressResult inboxByEmailAddressResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, inboxByEmailAddressResult, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InboxByEmailAddressResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="inboxByEmailAddressResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InboxByEmailAddressResult inboxByEmailAddressResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteBoolean("exists", inboxByEmailAddressResult.Exists);

            if (inboxByEmailAddressResult.InboxIdOption.IsSet)
                if (inboxByEmailAddressResult.InboxIdOption.Value != null)
                    writer.WriteString("inboxId", inboxByEmailAddressResult.InboxIdOption.Value.Value);
                else
                    writer.WriteNull("inboxId");
        }
    }
}
