/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = mailslurp.Client.OpenAPIDateConverter;

namespace mailslurp.Model
{
    /// <summary>
    /// Nested AND/OR match tree for inbox forwarders and repliers.
    /// </summary>
    [DataContract(Name = "InboxAutomationMatchOptions")]
    public partial class InboxAutomationMatchOptions : IValidatableObject
    {
        /// <summary>
        /// Boolean operator used to combine inbox automation match rules.
        /// </summary>
        /// <value>Boolean operator used to combine inbox automation match rules.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum OperatorEnum
        {
            /// <summary>
            /// Enum AND for value: AND
            /// </summary>
            [EnumMember(Value = "AND")]
            AND = 1,

            /// <summary>
            /// Enum OR for value: OR
            /// </summary>
            [EnumMember(Value = "OR")]
            OR = 2
        }


        /// <summary>
        /// Boolean operator used to combine inbox automation match rules.
        /// </summary>
        /// <value>Boolean operator used to combine inbox automation match rules.</value>
        [DataMember(Name = "operator", IsRequired = true, EmitDefaultValue = true)]
        public OperatorEnum Operator { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="InboxAutomationMatchOptions" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InboxAutomationMatchOptions() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InboxAutomationMatchOptions" /> class.
        /// </summary>
        /// <param name="varOperator">Boolean operator used to combine inbox automation match rules. (required).</param>
        /// <param name="matches">Leaf match rules in this group..</param>
        /// <param name="groups">Nested child groups..</param>
        public InboxAutomationMatchOptions(OperatorEnum varOperator = default, List<InboxAutomationMatchOption> matches = default, List<InboxAutomationMatchOptions> groups = default)
        {
            this.Operator = varOperator;
            this.Matches = matches;
            this.Groups = groups;
        }

        /// <summary>
        /// Leaf match rules in this group.
        /// </summary>
        /// <value>Leaf match rules in this group.</value>
        [DataMember(Name = "matches", EmitDefaultValue = true)]
        public List<InboxAutomationMatchOption> Matches { get; set; }

        /// <summary>
        /// Nested child groups.
        /// </summary>
        /// <value>Nested child groups.</value>
        [DataMember(Name = "groups", EmitDefaultValue = true)]
        public List<InboxAutomationMatchOptions> Groups { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InboxAutomationMatchOptions {\n");
            sb.Append("  Operator: ").Append(Operator).Append("\n");
            sb.Append("  Matches: ").Append(Matches).Append("\n");
            sb.Append("  Groups: ").Append(Groups).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
