// <auto-generated>
/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using mailslurp.Client;

namespace mailslurp.Model
{
    /// <summary>
    /// Paginated inbox connectors. Page index starts at zero. Projection results may omit larger entity fields. For fetching a full entity use the projection ID with individual method calls.
    /// </summary>
    public partial class PageConnector : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PageConnector" /> class.
        /// </summary>
        /// <param name="totalElements">totalElements</param>
        /// <param name="totalPages">totalPages</param>
        /// <param name="content">content</param>
        /// <param name="pageable">pageable</param>
        /// <param name="last">last</param>
        /// <param name="numberOfElements">numberOfElements</param>
        /// <param name="first">first</param>
        /// <param name="size">size</param>
        /// <param name="number">number</param>
        /// <param name="sort">sort</param>
        /// <param name="empty">empty</param>
        [JsonConstructor]
        public PageConnector(long totalElements, int totalPages, Option<List<ConnectorProjection>> content = default, Option<PageableObject> pageable = default, Option<bool?> last = default, Option<int?> numberOfElements = default, Option<bool?> first = default, Option<int?> size = default, Option<int?> number = default, Option<SortObject> sort = default, Option<bool?> empty = default)
        {
            TotalElements = totalElements;
            TotalPages = totalPages;
            ContentOption = content;
            PageableOption = pageable;
            LastOption = last;
            NumberOfElementsOption = numberOfElements;
            FirstOption = first;
            SizeOption = size;
            NumberOption = number;
            SortOption = sort;
            EmptyOption = empty;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets TotalElements
        /// </summary>
        [JsonPropertyName("totalElements")]
        public long TotalElements { get; set; }

        /// <summary>
        /// Gets or Sets TotalPages
        /// </summary>
        [JsonPropertyName("totalPages")]
        public int TotalPages { get; set; }

        /// <summary>
        /// Used to track the state of Content
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ConnectorProjection>> ContentOption { get; private set; }

        /// <summary>
        /// Gets or Sets Content
        /// </summary>
        [JsonPropertyName("content")]
        public List<ConnectorProjection> Content { get { return this.ContentOption; } set { this.ContentOption = new Option<List<ConnectorProjection>>(value); } }

        /// <summary>
        /// Used to track the state of Pageable
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<PageableObject> PageableOption { get; private set; }

        /// <summary>
        /// Gets or Sets Pageable
        /// </summary>
        [JsonPropertyName("pageable")]
        public PageableObject Pageable { get { return this.PageableOption; } set { this.PageableOption = new Option<PageableObject>(value); } }

        /// <summary>
        /// Used to track the state of Last
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> LastOption { get; private set; }

        /// <summary>
        /// Gets or Sets Last
        /// </summary>
        [JsonPropertyName("last")]
        public bool? Last { get { return this.LastOption; } set { this.LastOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of NumberOfElements
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> NumberOfElementsOption { get; private set; }

        /// <summary>
        /// Gets or Sets NumberOfElements
        /// </summary>
        [JsonPropertyName("numberOfElements")]
        public int? NumberOfElements { get { return this.NumberOfElementsOption; } set { this.NumberOfElementsOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of First
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> FirstOption { get; private set; }

        /// <summary>
        /// Gets or Sets First
        /// </summary>
        [JsonPropertyName("first")]
        public bool? First { get { return this.FirstOption; } set { this.FirstOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of Size
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SizeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Size
        /// </summary>
        [JsonPropertyName("size")]
        public int? Size { get { return this.SizeOption; } set { this.SizeOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of Number
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> NumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets Number
        /// </summary>
        [JsonPropertyName("number")]
        public int? Number { get { return this.NumberOption; } set { this.NumberOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of Sort
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SortObject> SortOption { get; private set; }

        /// <summary>
        /// Gets or Sets Sort
        /// </summary>
        [JsonPropertyName("sort")]
        public SortObject Sort { get { return this.SortOption; } set { this.SortOption = new Option<SortObject>(value); } }

        /// <summary>
        /// Used to track the state of Empty
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EmptyOption { get; private set; }

        /// <summary>
        /// Gets or Sets Empty
        /// </summary>
        [JsonPropertyName("empty")]
        public bool? Empty { get { return this.EmptyOption; } set { this.EmptyOption = new Option<bool?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PageConnector {\n");
            sb.Append("  TotalElements: ").Append(TotalElements).Append("\n");
            sb.Append("  TotalPages: ").Append(TotalPages).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  Pageable: ").Append(Pageable).Append("\n");
            sb.Append("  Last: ").Append(Last).Append("\n");
            sb.Append("  NumberOfElements: ").Append(NumberOfElements).Append("\n");
            sb.Append("  First: ").Append(First).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  Sort: ").Append(Sort).Append("\n");
            sb.Append("  Empty: ").Append(Empty).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PageConnector" />
    /// </summary>
    public class PageConnectorJsonConverter : JsonConverter<PageConnector>
    {
        /// <summary>
        /// Deserializes json to <see cref="PageConnector" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PageConnector Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> totalElements = default;
            Option<int?> totalPages = default;
            Option<List<ConnectorProjection>> content = default;
            Option<PageableObject> pageable = default;
            Option<bool?> last = default;
            Option<int?> numberOfElements = default;
            Option<bool?> first = default;
            Option<int?> size = default;
            Option<int?> number = default;
            Option<SortObject> sort = default;
            Option<bool?> empty = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "totalElements":
                            totalElements = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "totalPages":
                            totalPages = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "content":
                            content = new Option<List<ConnectorProjection>>(JsonSerializer.Deserialize<List<ConnectorProjection>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "pageable":
                            pageable = new Option<PageableObject>(JsonSerializer.Deserialize<PageableObject>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "last":
                            last = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "numberOfElements":
                            numberOfElements = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "first":
                            first = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "size":
                            size = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "number":
                            number = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "sort":
                            sort = new Option<SortObject>(JsonSerializer.Deserialize<SortObject>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "empty":
                            empty = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!totalElements.IsSet)
                throw new ArgumentException("Property is required for class PageConnector.", nameof(totalElements));

            if (!totalPages.IsSet)
                throw new ArgumentException("Property is required for class PageConnector.", nameof(totalPages));

            if (totalElements.IsSet && totalElements.Value == null)
                throw new ArgumentNullException(nameof(totalElements), "Property is not nullable for class PageConnector.");

            if (totalPages.IsSet && totalPages.Value == null)
                throw new ArgumentNullException(nameof(totalPages), "Property is not nullable for class PageConnector.");

            if (content.IsSet && content.Value == null)
                throw new ArgumentNullException(nameof(content), "Property is not nullable for class PageConnector.");

            if (pageable.IsSet && pageable.Value == null)
                throw new ArgumentNullException(nameof(pageable), "Property is not nullable for class PageConnector.");

            if (last.IsSet && last.Value == null)
                throw new ArgumentNullException(nameof(last), "Property is not nullable for class PageConnector.");

            if (numberOfElements.IsSet && numberOfElements.Value == null)
                throw new ArgumentNullException(nameof(numberOfElements), "Property is not nullable for class PageConnector.");

            if (first.IsSet && first.Value == null)
                throw new ArgumentNullException(nameof(first), "Property is not nullable for class PageConnector.");

            if (size.IsSet && size.Value == null)
                throw new ArgumentNullException(nameof(size), "Property is not nullable for class PageConnector.");

            if (number.IsSet && number.Value == null)
                throw new ArgumentNullException(nameof(number), "Property is not nullable for class PageConnector.");

            if (sort.IsSet && sort.Value == null)
                throw new ArgumentNullException(nameof(sort), "Property is not nullable for class PageConnector.");

            if (empty.IsSet && empty.Value == null)
                throw new ArgumentNullException(nameof(empty), "Property is not nullable for class PageConnector.");

            return new PageConnector(totalElements.Value.Value, totalPages.Value.Value, content, pageable, last, numberOfElements, first, size, number, sort, empty);
        }

        /// <summary>
        /// Serializes a <see cref="PageConnector" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pageConnector"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PageConnector pageConnector, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, pageConnector, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PageConnector" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pageConnector"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PageConnector pageConnector, JsonSerializerOptions jsonSerializerOptions)
        {
            if (pageConnector.ContentOption.IsSet && pageConnector.Content == null)
                throw new ArgumentNullException(nameof(pageConnector.Content), "Property is required for class PageConnector.");

            if (pageConnector.PageableOption.IsSet && pageConnector.Pageable == null)
                throw new ArgumentNullException(nameof(pageConnector.Pageable), "Property is required for class PageConnector.");

            if (pageConnector.SortOption.IsSet && pageConnector.Sort == null)
                throw new ArgumentNullException(nameof(pageConnector.Sort), "Property is required for class PageConnector.");

            writer.WriteNumber("totalElements", pageConnector.TotalElements);

            writer.WriteNumber("totalPages", pageConnector.TotalPages);

            if (pageConnector.ContentOption.IsSet)
            {
                writer.WritePropertyName("content");
                JsonSerializer.Serialize(writer, pageConnector.Content, jsonSerializerOptions);
            }
            if (pageConnector.PageableOption.IsSet)
            {
                writer.WritePropertyName("pageable");
                JsonSerializer.Serialize(writer, pageConnector.Pageable, jsonSerializerOptions);
            }
            if (pageConnector.LastOption.IsSet)
                writer.WriteBoolean("last", pageConnector.LastOption.Value.Value);

            if (pageConnector.NumberOfElementsOption.IsSet)
                writer.WriteNumber("numberOfElements", pageConnector.NumberOfElementsOption.Value.Value);

            if (pageConnector.FirstOption.IsSet)
                writer.WriteBoolean("first", pageConnector.FirstOption.Value.Value);

            if (pageConnector.SizeOption.IsSet)
                writer.WriteNumber("size", pageConnector.SizeOption.Value.Value);

            if (pageConnector.NumberOption.IsSet)
                writer.WriteNumber("number", pageConnector.NumberOption.Value.Value);

            if (pageConnector.SortOption.IsSet)
            {
                writer.WritePropertyName("sort");
                JsonSerializer.Serialize(writer, pageConnector.Sort, jsonSerializerOptions);
            }
            if (pageConnector.EmptyOption.IsSet)
                writer.WriteBoolean("empty", pageConnector.EmptyOption.Value.Value);
        }
    }
}
