/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = mailslurp.Client.OpenAPIDateConverter;

namespace mailslurp.Model
{
    /// <summary>
    /// TenantReputationFindingDto
    /// </summary>
    [DataContract(Name = "TenantReputationFindingDto")]
    public partial class TenantReputationFindingDto : IValidatableObject
    {
        /// <summary>
        /// Defines AccountRegion
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AccountRegionEnum
        {
            /// <summary>
            /// Enum USWEST2ACCOUNTSTAGING for value: US_WEST_2_ACCOUNT_STAGING
            /// </summary>
            [EnumMember(Value = "US_WEST_2_ACCOUNT_STAGING")]
            USWEST2ACCOUNTSTAGING = 1,

            /// <summary>
            /// Enum USEAST1ACCOUNTSTAGING for value: US_EAST_1_ACCOUNT_STAGING
            /// </summary>
            [EnumMember(Value = "US_EAST_1_ACCOUNT_STAGING")]
            USEAST1ACCOUNTSTAGING = 2,

            /// <summary>
            /// Enum EUWEST1ACCOUNTSTAGING for value: EU_WEST_1_ACCOUNT_STAGING
            /// </summary>
            [EnumMember(Value = "EU_WEST_1_ACCOUNT_STAGING")]
            EUWEST1ACCOUNTSTAGING = 3,

            /// <summary>
            /// Enum USWEST2ACCOUNTSES1 for value: US_WEST_2_ACCOUNT_SES_1
            /// </summary>
            [EnumMember(Value = "US_WEST_2_ACCOUNT_SES_1")]
            USWEST2ACCOUNTSES1 = 4,

            /// <summary>
            /// Enum EUWEST1ACCOUNTSES1 for value: EU_WEST_1_ACCOUNT_SES_1
            /// </summary>
            [EnumMember(Value = "EU_WEST_1_ACCOUNT_SES_1")]
            EUWEST1ACCOUNTSES1 = 5,

            /// <summary>
            /// Enum USWEST2ACCOUNTSES2 for value: US_WEST_2_ACCOUNT_SES_2
            /// </summary>
            [EnumMember(Value = "US_WEST_2_ACCOUNT_SES_2")]
            USWEST2ACCOUNTSES2 = 6,

            /// <summary>
            /// Enum EUWEST1ACCOUNTSES2 for value: EU_WEST_1_ACCOUNT_SES_2
            /// </summary>
            [EnumMember(Value = "EU_WEST_1_ACCOUNT_SES_2")]
            EUWEST1ACCOUNTSES2 = 7,

            /// <summary>
            /// Enum USWEST2ACCOUNTBYTEWISE for value: US_WEST_2_ACCOUNT_BYTEWISE
            /// </summary>
            [EnumMember(Value = "US_WEST_2_ACCOUNT_BYTEWISE")]
            USWEST2ACCOUNTBYTEWISE = 8,

            /// <summary>
            /// Enum EUWEST1ACCOUNTBYTEWISE for value: EU_WEST_1_ACCOUNT_BYTEWISE
            /// </summary>
            [EnumMember(Value = "EU_WEST_1_ACCOUNT_BYTEWISE")]
            EUWEST1ACCOUNTBYTEWISE = 9,

            /// <summary>
            /// Enum USWEST2 for value: US_WEST_2
            /// </summary>
            [EnumMember(Value = "US_WEST_2")]
            USWEST2 = 10,

            /// <summary>
            /// Enum EUWEST1 for value: EU_WEST_1
            /// </summary>
            [EnumMember(Value = "EU_WEST_1")]
            EUWEST1 = 11,

            /// <summary>
            /// Enum USEAST1 for value: US_EAST_1
            /// </summary>
            [EnumMember(Value = "US_EAST_1")]
            USEAST1 = 12
        }


        /// <summary>
        /// Gets or Sets AccountRegion
        /// </summary>
        [DataMember(Name = "accountRegion", IsRequired = true, EmitDefaultValue = true)]
        public AccountRegionEnum AccountRegion { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TenantReputationFindingDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TenantReputationFindingDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TenantReputationFindingDto" /> class.
        /// </summary>
        /// <param name="accountRegion">accountRegion (required).</param>
        /// <param name="tenantName">tenantName (required).</param>
        /// <param name="tenantArn">tenantArn.</param>
        /// <param name="type">type.</param>
        /// <param name="impact">impact.</param>
        /// <param name="status">status.</param>
        /// <param name="description">description.</param>
        /// <param name="createdTimestamp">createdTimestamp.</param>
        /// <param name="lastUpdatedTimestamp">lastUpdatedTimestamp.</param>
        public TenantReputationFindingDto(AccountRegionEnum accountRegion = default, string tenantName = default, string tenantArn = default, string type = default, string impact = default, string status = default, string description = default, DateTime createdTimestamp = default, DateTime lastUpdatedTimestamp = default)
        {
            this.AccountRegion = accountRegion;
            // to ensure "tenantName" is required (not null)
            if (tenantName == null)
            {
                throw new ArgumentNullException("tenantName is a required property for TenantReputationFindingDto and cannot be null");
            }
            this.TenantName = tenantName;
            this.TenantArn = tenantArn;
            this.Type = type;
            this.Impact = impact;
            this.Status = status;
            this.Description = description;
            this.CreatedTimestamp = createdTimestamp;
            this.LastUpdatedTimestamp = lastUpdatedTimestamp;
        }

        /// <summary>
        /// Gets or Sets TenantName
        /// </summary>
        [DataMember(Name = "tenantName", IsRequired = true, EmitDefaultValue = true)]
        public string TenantName { get; set; }

        /// <summary>
        /// Gets or Sets TenantArn
        /// </summary>
        [DataMember(Name = "tenantArn", EmitDefaultValue = false)]
        public string TenantArn { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Impact
        /// </summary>
        [DataMember(Name = "impact", EmitDefaultValue = false)]
        public string Impact { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets CreatedTimestamp
        /// </summary>
        [DataMember(Name = "createdTimestamp", EmitDefaultValue = false)]
        public DateTime CreatedTimestamp { get; set; }

        /// <summary>
        /// Gets or Sets LastUpdatedTimestamp
        /// </summary>
        [DataMember(Name = "lastUpdatedTimestamp", EmitDefaultValue = false)]
        public DateTime LastUpdatedTimestamp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TenantReputationFindingDto {\n");
            sb.Append("  AccountRegion: ").Append(AccountRegion).Append("\n");
            sb.Append("  TenantName: ").Append(TenantName).Append("\n");
            sb.Append("  TenantArn: ").Append(TenantArn).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Impact: ").Append(Impact).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  CreatedTimestamp: ").Append(CreatedTimestamp).Append("\n");
            sb.Append("  LastUpdatedTimestamp: ").Append(LastUpdatedTimestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
