/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using mailslurp.Client;
using mailslurp.Api;
// uncomment below to import models
//using mailslurp.Model;

namespace mailslurp.Test.Api
{
    /// <summary>
    ///  Class for testing CampaignProbeControllerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CampaignProbeControllerApiTests : IDisposable
    {
        private CampaignProbeControllerApi instance;

        public CampaignProbeControllerApiTests()
        {
            instance = new CampaignProbeControllerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CampaignProbeControllerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CampaignProbeControllerApi
            //Assert.IsType<CampaignProbeControllerApi>(instance);
        }

        /// <summary>
        /// Test CreateCampaignProbe
        /// </summary>
        [Fact]
        public void CreateCampaignProbeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateCampaignProbeOptions createCampaignProbeOptions = null;
            //var response = instance.CreateCampaignProbe(createCampaignProbeOptions);
            //Assert.IsType<CampaignProbeDto>(response);
        }

        /// <summary>
        /// Test DeleteCampaignProbe
        /// </summary>
        [Fact]
        public void DeleteCampaignProbeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid probeId = null;
            //instance.DeleteCampaignProbe(probeId);
        }

        /// <summary>
        /// Test GetCampaignProbe
        /// </summary>
        [Fact]
        public void GetCampaignProbeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid probeId = null;
            //var response = instance.GetCampaignProbe(probeId);
            //Assert.IsType<CampaignProbeDto>(response);
        }

        /// <summary>
        /// Test GetCampaignProbeInsights
        /// </summary>
        [Fact]
        public void GetCampaignProbeInsightsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid probeId = null;
            //DateTime? since = null;
            //DateTime? before = null;
            //var response = instance.GetCampaignProbeInsights(probeId, since, before);
            //Assert.IsType<CampaignProbeInsightsDto>(response);
        }

        /// <summary>
        /// Test GetCampaignProbeRuns
        /// </summary>
        [Fact]
        public void GetCampaignProbeRunsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid probeId = null;
            //DateTime? since = null;
            //DateTime? before = null;
            //string status = null;
            //int? limit = null;
            //var response = instance.GetCampaignProbeRuns(probeId, since, before, status, limit);
            //Assert.IsType<List<CampaignProbeRunDto>>(response);
        }

        /// <summary>
        /// Test GetCampaignProbeSeries
        /// </summary>
        [Fact]
        public void GetCampaignProbeSeriesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid probeId = null;
            //DateTime? since = null;
            //DateTime? before = null;
            //string bucket = null;
            //var response = instance.GetCampaignProbeSeries(probeId, since, before, bucket);
            //Assert.IsType<CampaignProbeSeriesDto>(response);
        }

        /// <summary>
        /// Test GetCampaignProbes
        /// </summary>
        [Fact]
        public void GetCampaignProbesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetCampaignProbes();
            //Assert.IsType<List<CampaignProbeDto>>(response);
        }

        /// <summary>
        /// Test RunCampaignProbeNow
        /// </summary>
        [Fact]
        public void RunCampaignProbeNowTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid probeId = null;
            //CreateCampaignProbeRunOptions createCampaignProbeRunOptions = null;
            //var response = instance.RunCampaignProbeNow(probeId, createCampaignProbeRunOptions);
            //Assert.IsType<CampaignProbeRunNowResult>(response);
        }

        /// <summary>
        /// Test RunDueCampaignProbes
        /// </summary>
        [Fact]
        public void RunDueCampaignProbesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? maxRuns = null;
            //var response = instance.RunDueCampaignProbes(maxRuns);
            //Assert.IsType<CampaignProbeRunDueResult>(response);
        }

        /// <summary>
        /// Test UpdateCampaignProbe
        /// </summary>
        [Fact]
        public void UpdateCampaignProbeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid probeId = null;
            //UpdateCampaignProbeOptions updateCampaignProbeOptions = null;
            //var response = instance.UpdateCampaignProbe(probeId, updateCampaignProbeOptions);
            //Assert.IsType<CampaignProbeDto>(response);
        }
    }
}
